import AnimatedText from "@/Components/AnimatedText";
import { LinkArrow } from "@/Components/Icons";
import Layout from "@/Components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Profilepic from "../public/images/profile/Bg-removed SideImage-Main (1).png";
import { RiContactsBookFill } from "react-icons/ri";
import LightBulb from "../public/images/svgs/miscellaneous_icons_1.svg";
import Transitions from "@/Components/Transitions";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

export default function Home() {
  const img = "https://media.tenor.com/NOYF3f82b_gAAAAC/programmer.gif";
  return (
    <>
      <Head>
        <title>GOPI | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transitions />
      <Navbar />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light h-screen">
        <Layout className="pt-2 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col ">
            <div className="w-1/2 md:w-full">
              <Image
                src={Profilepic}
                alt={"DEVELOPER IMAGE"}
                className="w-full h-auto lg:w-full md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Hey, there. I am T C Gopal"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs ">
                As a skilled Software developer, I am dedicated to turning ideas
                into innovative web applications. Explore my latest projects,
                showcasing my expertise in web development and flexibility in
                learning any new technologies.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="https://drive.google.com/file/d/1BoufjdYrCNpzRj-SDy90o2BGpMsubGu1/view"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  <p>RESUME</p> <LinkArrow />
                </Link>
                <Link
                  href={
                    "https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=gopigaurav9@gmail.com"
                  }
                  target="_blank"
                  className="ml-4 flex items-center bg-dark text-light p-2 rounded-lg text-lg font-semibold dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  <p>CONTACT</p>
                  <RiContactsBookFill className="ml-2" />
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
      <section></section>
    </>
  );
}
